import * as Colors from '@tamagui/colors';
import { createThemes } from '@tamagui/config/v4';
import { createTamagui } from 'tamagui';
import { outfitFont } from './src/theme/fonts';

const darkPalette = [
  '#050505',
  '#151515',
  '#191919',
  '#232323',
  '#282828',
  '#323232',
  '#424242',
  '#494949',
  '#545454',
  '#626262',
  '#a5a5a5',
  '#fff',
];

const lightPalette = [
  '#fff',
  '#f8f8f8',
  'hsl(0, 0%, 96.3%)',
  'hsl(0, 0%, 94.1%)',
  'hsl(0, 0%, 92.0%)',
  'hsl(0, 0%, 90.0%)',
  'hsl(0, 0%, 88.5%)',
  'hsl(0, 0%, 81.0%)',
  'hsl(0, 0%, 56.1%)',
  'hsl(0, 0%, 50.3%)',
  'hsl(0, 0%, 42.5%)',
  'hsl(0, 0%, 9.0%)',
];

const lightShadows = {
  shadow1: 'rgba(0,0,0,0.04)',
  shadow2: 'rgba(0,0,0,0.08)',
  shadow3: 'rgba(0,0,0,0.16)',
  shadow4: 'rgba(0,0,0,0.24)',
  shadow5: 'rgba(0,0,0,0.32)',
  shadow6: 'rgba(0,0,0,0.4)',
};

const darkShadows = {
  shadow1: 'rgba(0,0,0,0.2)',
  shadow2: 'rgba(0,0,0,0.3)',
  shadow3: 'rgba(0,0,0,0.4)',
  shadow4: 'rgba(0,0,0,0.5)',
  shadow5: 'rgba(0,0,0,0.6)',
  shadow6: 'rgba(0,0,0,0.7)',
};

const extraColors = {
  black1: darkPalette[0],
  black2: darkPalette[1],
  black3: darkPalette[2],
  black4: darkPalette[3],
  black5: darkPalette[4],
  black6: darkPalette[5],
  black7: darkPalette[6],
  black8: darkPalette[7],
  black9: darkPalette[8],
  black10: darkPalette[9],
  black11: darkPalette[10],
  black12: darkPalette[11],
  white1: lightPalette[0],
  white2: lightPalette[1],
  white3: lightPalette[2],
  white4: lightPalette[3],
  white5: lightPalette[4],
  white6: lightPalette[5],
  white7: lightPalette[6],
  white8: lightPalette[7],
  white9: lightPalette[8],
  white10: lightPalette[9],
  white11: lightPalette[10],
  white12: lightPalette[11],
};

const generatedThemes = createThemes({
  base: {
    palette: {
      dark: darkPalette,
      light: lightPalette,
    },

    // for values we don't want being inherited onto sub-themes
    extra: {
      light: {
        ...Colors.blue,
        ...Colors.green,
        ...Colors.red,
        ...Colors.yellow,
        ...lightShadows,
        ...extraColors,
        shadowColor: lightShadows.shadow1,
        // Custom theme colors
        primary: '#0891B2',
        primaryDark: '#1F2937',
        primaryLight: '#06B6D4',
        secondary: '#14B8A6',
        secondaryDark: '#0D9488',
        secondaryLight: '#2DD4BF',
        background: '#FAFBFC',
        backgroundSecondary: '#F3F4F6',
        surface: '#FFFFFF',
        surfaceVariant: '#F8F9FA',
        white: '#FFFFFF',
        black: '#000000',
        link: '#0891B2',
        textPrimary: '#1F2937',
        textSecondary: '#6B7280',
        textHighlight: '#0891B2',
        textDisabled: '#9CA3AF',
        textCaption: '#9CA3AF',
        textGreen: '#059669',
        textOnSurface: '#1F2937',
        textMuted: '#F9FAFB',
        borderLight: '#F3F4F6',
        borderMedium: '#E5E7EB',
        borderDark: '#D1D5DB',
        statusSuccess: '#10B981',
        statusWarning: '#F59E0B',
        statusError: '#EF4444',
        statusInfo: '#06B6D4',
        statusDisabled: '#D1D5DB',
      },
      dark: {
        ...Colors.blueDark,
        ...Colors.greenDark,
        ...Colors.redDark,
        ...Colors.yellowDark,
        ...darkShadows,
        ...extraColors,
        shadowColor: darkShadows.shadow1,
        // Custom theme colors (same for now, can be adjusted for dark mode later)
        primary: '#0891B2',
        primaryDark: '#1F2937',
        primaryLight: '#06B6D4',
        secondary: '#14B8A6',
        secondaryDark: '#0D9488',
        secondaryLight: '#2DD4BF',
        background: '#FAFBFC',
        surface: '#FFFFFF',
        surfaceVariant: '#F8F9FA',
        white: '#FFFFFF',
        black: '#000000',
        link: '#0891B2',
        textPrimary: '#1F2937',
        textSecondary: '#6B7280',
        textHighlight: '#0891B2',
        textDisabled: '#9CA3AF',
        textCaption: '#9CA3AF',
        textGreen: '#059669',
        textOnSurface: '#1F2937',
        textMuted: '#F9FAFB',
        borderLight: '#F3F4F6',
        borderMedium: '#E5E7EB',
        borderDark: '#D1D5DB',
        statusSuccess: '#10B981',
        statusWarning: '#F59E0B',
        statusError: '#EF4444',
        statusInfo: '#06B6D4',
        statusDisabled: '#D1D5DB',
      },
    },
  },

  // inverse accent theme
  accent: {
    palette: {
      dark: lightPalette,
      light: darkPalette,
    },
  },

  childrenThemes: {
    blue: {
      palette: {
        dark: Object.values(Colors.blueDark),
        light: Object.values(Colors.blue),
      },
    },
    red: {
      palette: {
        dark: Object.values(Colors.redDark),
        light: Object.values(Colors.red),
      },
    },
    yellow: {
      palette: {
        dark: Object.values(Colors.yellowDark),
        light: Object.values(Colors.yellow),
      },
    },
    green: {
      palette: {
        dark: Object.values(Colors.greenDark),
        light: Object.values(Colors.green),
      },
    },
  },
});

export type TamaguiThemes = typeof generatedThemes;

/**
 * This is an optional production optimization: themes JS can get to 20Kb or more.
 * Tamagui has ~1Kb of logic to hydrate themes from CSS, so you can remove the JS.
 * So long as you server render your Tamagui CSS, this will save you bundle size:
 */
export const themes: TamaguiThemes =
  process.env.TAMAGUI_ENVIRONMENT === 'client' && process.env.NODE_ENV === 'production'
    ? {}
    : (generatedThemes as any);

// Create the complete Tamagui config
// Using default tokens, fonts, and media from Tamagui
const config = createTamagui({
  themes,
  settings: {
    defaultFont: 'body',
  },
  tokens: {
    size: {
      0: 0,
      0.25: 1,
      0.5: 2,
      0.75: 3,
      1: 4,
      1.5: 6,
      2: 8,
      2.5: 10,
      3: 12,
      3.5: 14,
      4: 16,
      4.5: 18,
      5: 20,
      6: 24,
      7: 28,
      8: 32,
      9: 36,
      10: 40,
      11: 44,
      12: 48,
      14: 56,
      16: 64,
      20: 80,
      24: 96,
      28: 112,
      32: 128,
      36: 144,
      40: 160,
      44: 176,
      48: 192,
      52: 208,
      56: 224,
      60: 240,
      64: 256,
      72: 288,
      80: 320,
      96: 384,
      true: 16,
    },
    space: {
      0: 0,
      0.25: 1,
      0.5: 2,
      0.75: 3,
      1: 4,
      1.5: 6,
      2: 8,
      2.5: 10,
      3: 12,
      3.5: 14,
      4: 16,
      4.5: 18,
      5: 20,
      6: 24,
      7: 28,
      8: 32,
      9: 36,
      10: 40,
      11: 44,
      12: 48,
      14: 56,
      16: 64,
      20: 80,
      24: 96,
      28: 112,
      32: 128,
      36: 144,
      40: 160,
      44: 176,
      48: 192,
      52: 208,
      56: 224,
      60: 240,
      64: 256,
      72: 288,
      80: 320,
      96: 384,
      true: 16,
    },
    radius: {
      0: 0,
      1: 3,
      2: 5,
      3: 7,
      4: 9,
      5: 10,
      6: 16,
      7: 19,
      8: 22,
      9: 26,
      10: 34,
      11: 42,
      12: 50,
      round: 1000,
      true: 7,
    },
    zIndex: {
      0: 0,
      1: 100,
      2: 200,
      3: 300,
      4: 400,
      5: 500,
      true: 1,
    },
    color: {
      transparent: 'transparent',
    },
  },
  fonts: {
    body: outfitFont,
    heading: outfitFont,
  },
  media: {
    xs: { maxWidth: 660 },
    sm: { maxWidth: 800 },
    md: { maxWidth: 1020 },
    lg: { maxWidth: 1280 },
    xl: { maxWidth: 1420 },
    xxl: { maxWidth: 1600 },
    gtXs: { minWidth: 660 + 1 },
    gtSm: { minWidth: 800 + 1 },
    gtMd: { minWidth: 1020 + 1 },
    gtLg: { minWidth: 1280 + 1 },
    short: { maxHeight: 820 },
    tall: { minHeight: 820 },
    hoverNone: { hover: 'none' },
    pointerCoarse: { pointer: 'coarse' },
  },
  shorthands: {
    px: 'paddingHorizontal',
    py: 'paddingVertical',
    mx: 'marginHorizontal',
    my: 'marginVertical',
    bg: 'backgroundColor',
    br: 'borderRadius',
    bw: 'borderWidth',
    bc: 'borderColor',
    w: 'width',
    h: 'height',
    m: 'margin',
    p: 'padding',
    mt: 'marginTop',
    mr: 'marginRight',
    mb: 'marginBottom',
    ml: 'marginLeft',
    pt: 'paddingTop',
    pr: 'paddingRight',
    pb: 'paddingBottom',
    pl: 'paddingLeft',
    f: 'flex',
    fd: 'flexDirection',
    fw: 'flexWrap',
    ai: 'alignItems',
    jc: 'justifyContent',
    ac: 'alignContent',
    as: 'alignSelf',
    fg: 'flexGrow',
    fs: 'flexShrink',
    fb: 'flexBasis',
    bsis: 'flexBasis',
    op: 'opacity',
    pe: 'pointerEvents',
    cur: 'cursor',
    us: 'userSelect',
    col: 'color',
    ff: 'fontFamily',
    fos: 'fontSize',
    fost: 'fontStyle',
    fow: 'fontWeight',
    ls: 'letterSpacing',
    lh: 'lineHeight',
    ta: 'textAlign',
    tt: 'textTransform',
    td: 'textDecorationLine',
    z: 'zIndex',
    zi: 'zIndex',
    ov: 'overflow',
    ox: 'overflowX',
    oy: 'overflowY',
    dsp: 'display',
    ww: 'wordWrap',
  },
});

export default config;

// Export types for TypeScript
export type Conf = typeof config;

declare module 'tamagui' {
  interface TamaguiCustomConfig extends Conf {}
}
